# Generated by Django 3.0.3 on 2020-02-07 07:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tag', models.TextField(max_length=100)),
                ('ingredients', models.TextField()),
                ('imageUrl', models.TextField()),
                ('direction', models.TextField()),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeToCook', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Author')),
            ],
        ),
    ]
